name: CI
on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      # Crear el directorio sshx
      - name: Create sshx directory
        run: mkdir sshx

      # Descargar el archivo .zip en la carpeta sshx
      - name: Download sshx.zip
        run: |
          curl -L -o sshx/sshx-x86_64-pc-windows-msvc.zip https://sshx.s3.amazonaws.com/sshx-x86_64-pc-windows-msvc.zip

      # Descomprimir el archivo .zip
      - name: Unzip sshx.zip
        run: |
          powershell -Command "Expand-Archive -Path 'sshx/sshx-x86_64-pc-windows-msvc.zip' -DestinationPath 'sshx'"

      # Ejecutar sshx.exe y mostrar la salida
      - name: Run sshx.exe
        run: |
          cd sshx
          .\sshx.exe
