name: OHHYEAH
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Instalar ZeroTier
      - run: |
          curl -s https://install.zerotier.com | sudo bash
          
      # Unirse a la red ZeroTier
      - run: |
          sudo zerotier-cli join 60ee7c034a5d8b54

      # Crear un nuevo usuario llamado 'xen' y establecer la contraseña
      - run: |
          sudo adduser --disabled-password --gecos "" xen
          echo "xen:xen24" | sudo chpasswd

      # Agregar el usuario 'xen' al grupo sudo
      - run: |
          sudo usermod -aG sudo xen

      # Instalar Neofetch
      - run: |
          sudo apt update
          sudo apt install -y neofetch

      # Instalar Java JDK 21
      - run: |
          sudo apt install -y wget
          wget https://download.oracle.com/java/21/archive/jdk-21_linux-x64_bin.deb
          sudo apt install -y ./jdk-21_linux-x64_bin.deb
          rm jdk-21_linux-x64_bin.deb # Elimina el archivo descargado después de la instalación

      # Mantener la sesión activa con un bucle infinito
      - run: |
          echo "Manteniendo la sesión activa. Presiona Ctrl+C para salir."
          while true; do sleep 1; done
